version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-spring-demo
    environment:
      POSTGRES_DB: students_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data:
